GO

CREATE DATABASE [Tourist Agency]

USE [Tourist Agency]

GO

CREATE TABLE Countries 
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR (50) NOT NULL
)


CREATE TABLE Destinations
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR (50) NOT NULL,
	CountryId INT FOREIGN KEY REFERENCES Countries (Id)
)

CREATE TABLE Rooms
(
	Id INT PRIMARY KEY IDENTITY,
	[Type] VARCHAR (40) NOT NULL,
	Price DECIMAL (18,2) NOT NULL,
	BedCount INT CHECK (BedCount > 0 AND BedCount <= 10) NOT NULL
)